const mongoose = require("mongoose");

const experienceSchema = new mongoose.Schema(
  {
    company: String,
    role: String,
    year: String,
    description: String,
  },
  { _id: false }
);

const projectSchema = new mongoose.Schema(
  {
    title: String,
    description: String,
    link: String,
    image: String,
  },
  { _id: false }
);

const referenceSchema = new mongoose.Schema(
  {
    name: String,
    company: String,
    position: String,
    contactNo: String,
    email: String,
  },
  { _id: false }
);

const portfolioSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      unique: true,
    },
    about: {
      name: String,
      role: String,
      description: String,
      profileImage: String,
    },
    skills: [String],
    experience: [experienceSchema],
    projects: [projectSchema],
    references: [referenceSchema],
    social: {
      email: String,
      github: String,
      linkedin: String,
      website: String,
    },
    theme: { type: String, default: "template1" },
    templateId: { type: mongoose.Schema.Types.ObjectId, default: null },
    customDesign: {
      // Custom design configuration generated by AI
      isCustom: { type: Boolean, default: false },
      colors: {
        primary: { type: String, default: "#4f46e5" },
        secondary: { type: String, default: "#7c3aed" },
        accent: { type: String, default: "#ec4899" },
        background: { type: String, default: "#ffffff" },
        text: { type: String, default: "#1e293b" },
      },
      fonts: {
        heading: { type: String, default: "sans-serif" },
        body: { type: String, default: "sans-serif" },
      },
      layout: { type: String, default: "standard" }, // standard, sidebar, grid, centered
      style: { type: String, default: "modern" }, // modern, classic, minimal, creative, bold
      designDescription: { type: String }, // Original design description from user
    },
  },
  { timestamps: true }
);

const Portfolio = mongoose.model("Portfolio", portfolioSchema);

module.exports = Portfolio;


